name: Build container test image
on:
  push:
    paths:
      - .github/Dockerfile
  pull_request:
    paths:
      - .github/Dockerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cogitri/gnome-software-plugin-apk-ci
  VERSION: 43

jobs:
  build-test-and-push-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: cogitri
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ env.VERSION}}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .github/
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and test plugin
        run: docker run --mount type=bind,src=${{ github.workspace }},dst=/repo --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ env.VERSION}} /bin/ash -c "cd repo && meson build && ninja -C build && dbus-daemon --system --fork --nopidfile && dbus-run-session -- meson test -v -C build"

      - name: Push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .github/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
