name: Run tests for Spracherkennung
on: pull_request_target

jobs:
  test:
    name: Tests
    container:
      image: ghcr.io/cogitri/gnome-software-plugin-apk-ci:latest
      credentials:
        username: cogitri
        password: ${{ secrets.DOCKER_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: meson build && ninja -C build

      - name: Test
        run: meson test -v -C build
