name: Run tests
on:
  pull_request_target:
    paths-ignore:
      - .github/Dockerfile # There is no reason to run if the container was updated

jobs:
  test:
    name: Tests
    container:
      image: ghcr.io/cogitri/gnome-software-plugin-apk-ci:41
      credentials:
        username: cogitri
        password: ${{ secrets.DOCKER_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build
        run: meson build && ninja -C build

      - name: Test
        run: meson test -v -C build
